[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas",
    "seaborn",
    "numpy",
    "torch",
    "matplotlib",
    "textwrap",
    "cycler"
]
build-backend = "setuptools.build_meta"
